language: php
os: linux
dist: bionic

cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  fast_finish: true
  include:
    - php: 7.2
#    - php: 7.2
#      env: deps=low
#    - php: 7.3
#    - php: 7.4
#  allow_failures:
#    - php: 7.2
#      env: deps=low

before_install:
  - echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  #- pecl install swoole --ignore-errors

install:
  - if [ "$deps" == "low" ]; then travis_retry composer update --prefer-dist --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then travis_retry composer install --prefer-dist; fi

before_script:
  - php --ri swoole

script: composer travis
